// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/Chart/BarChart.vue')['default']
    Earth: typeof import('./src/components/Earth/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Game: typeof import('./src/components/Game/index.vue')['default']
    Item: typeof import('./src/components/Game/item.vue')['default']
    LineChart: typeof import('./src/components/Chart/LineChart.vue')['default']
    PieChart: typeof import('./src/components/Chart/PieChart.vue')['default']
    ThemeColorPicker: typeof import('./src/components/ThemeColorPicker/index.vue')['default']
    Undone: typeof import('./src/components/Undone/index.vue')['default']
    Waves: typeof import('./src/components/Waves/index.vue')['default']
  }
}

export { }
